### ISSUE TITLE
[Question] Will this work with VirtualMIDISynth?

### ISSUE THREAD

**Issue by TheSystemGuy1337** [Didkrak/Midi-Keyboard#2]
**Don't know where to ask but might just ask here**

I don't own a MIDI keyboard but I want run-of-the-mill .mid files translated into keyboard format MAS supports. _Does this addon allow that or do I need to buy a MIDI keyboard or emulate said keyboard?_

**Comment by Didkrak** [comment]
I'm not familiar with VirtualMIDISynth. but after a quick read of their main page it sounds like it is an output for MIDI, not an input. So made for playing midi. So are you asking for a way to read from a pre-made midi file and play that recorded song on Monikas piano?

If so, as is this program won't do it. It has to connect to a midi input and reads from it in real time. You could use the keyboard press portion of this code and make your own code for doing that though. You'd just need to read in the midi file then make a keyboard press for every midi event, with a small time delay between the events (could get the time delay to match that in the midi file too).

I don't really see the point in doing this though, aside from I suppose testing piano songs in MAS without having to play it all yourself. There are easier ways to listen to the music with her, and easier ways to cheat playing the songs too (if your goal isn't to test the full properly played song).

**Comment by TheSystemGuy1337** [comment]
_Well, OK. I might just make it as a passthrough, not a .mid player since_ **this add-on doesn't allow for it. I highly doubt someone will ever make it because it's complicated.**


Thanks for the response, closing as impossible
